config/routes.rb
Geolocation::Engine.routes.draw do
  resources :locations, only: ['index', 'show']
  get '/ip_address/:ip_address' => 'locations#ip_address', as: 'ip_address', constraints: { :ip_address => /[^\/]+/ }
  post '/import_data' => 'locations#import_data'
end

app/models/geolocation/application_record.rb
module Geolocation
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/geolocation/location.rb
module Geolocation
  class LatitudeValidator < ActiveModel::Validator
    def validate(record)
      if !record.latitude.blank? && (record.latitude < -90 || record.latitude > 90)
        record.errors[:latitude] << 'must lie between -90 and +90'
      end
    end
  end

  class LongitudeValidator < ActiveModel::Validator
    def validate(record)
      if !record.longitude.blank? && (record.longitude < -180 || record.longitude > 180)
        record.errors[:longitude] << 'must lie between -180 and +180'
      end
    end
  end

  class Location < ApplicationRecord
    include ActiveModel::Validations
    validates_with LatitudeValidator
    validates_with LongitudeValidator

    validates :ip_address, :country, presence: true
    validates :latitude, :longitude, :mystery_value, presence: true, allow_blank: true
    validates :country_code, format: { :with => /\A[A-Z][A-Z]\z/i, message: 'only allows two letters' }, allow_blank: true
    validates :city, uniqueness: {scope: [:country_code, :country]}, allow_blank: true
  end
end

app/controllers/geolocation/application_controller.rb
module Geolocation
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def render_json_error(message, status)
      render json: { errors: [message] }, status: status
    end
  end
end

app/controllers/geolocation/locations_controller.rb
require 'csv'

require_dependency "geolocation/application_controller"

module Geolocation
  class LocationsController < ApplicationController
    # TODO: implement authentication using apikey
    skip_before_action :verify_authenticity_token
    before_action :set_location, only: [:show]

    # GET /locations
    def index
      @locations = Location.all
    end

    # GET /locations/1
    def show
    end

    def ip_address
      begin
        location = Location.find_by(ip_address: params[:ip_address])
        if location
          render json: { location: location }
        else
          render_json_error('404 Not Found', :not_found)
        end
      rescue ActiveRecord::StatementInvalid
        render_json_error('422 Invalid IP Address', :unprocessable_entity)
      end
    end

    # POST /import_data
    def import_data

      # Get necessary configuration parameters, overruled by query parameters if present.
      config = Geolocation.configuration
      file_name = params[:file_name] || config.file_name
      upload_dir = params[:upload_dir] || config.upload_dir

      if params[:allow_blank]
        allow_blank = params[:allow_blank] == 'true'
      else
        allow_blank = config.allow_blank
      end

      if params[:delete_all]
        delete_all = params[:delete_all] == 'true'
      else
        delete_all = config.delete_all
      end

      if params[:max_lines]
        max_lines = params[:max_lines]
      else
        max_lines = config.max_lines
      end
      max_lines = max_lines.to_i

      file_name_path = "#{upload_dir}/#{file_name}"
      full_path = "#{Rails.root}/#{file_name_path}"

      Location.delete_all if delete_all

      # Stopwatch for this transaction
      start = Time.now

      line = 0
      nok = 0
      errors = []

      begin
        CSV.foreach(full_path, headers: true) do |row|
          line = line + 1
          break if max_lines != 0 && line > max_lines
          location_hash = row.to_hash
          begin
            Location.create!(location_hash)
          rescue ActiveRecord::RecordInvalid => e
            nok = nok + 1
            errors.push({
              line: line,
              values: location_hash.values.join(','),
              messages: e.record.errors.messages
            })
          end
        end

        # Statistics
        now = Time.now
        elapsed = now - start

        render json: {
            import_data: {
                file_name: file_name,
                upload_dir: upload_dir,
                allow_blank: allow_blank,
                delete_all: delete_all,
                max_lines: max_lines,
                stopwatch: {
                    started: start.to_s,
                    finished: now.to_s,
                    elapsed: elapsed.to_s
                },
                records: {
                    total: line,
                    ok: line - nok,
                    nok: nok,
                    errors: errors
                }
            }
        }
      rescue Errno::ENOENT
        render_json_error('422 No such file or directory', :unprocessable_entity)
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_location
        @location = Location.find(params[:id])
      end
  end
end

app/helpers/geolocation/application_helper.rb
module Geolocation
  module ApplicationHelper
  end
end

app/helpers/geolocation/locations_helper.rb
module Geolocation
  module LocationsHelper
  end
end

app/views/geolocation/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_address %>
    <%= f.text_field :ip_address %>
  </div>

  <div class="field">
    <%= f.label :country_code %>
    <%= f.text_field :country_code %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :mystery_value %>
    <%= f.number_field :mystery_value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geolocation/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Ip address</th>
      <th>Country code</th>
      <th>Country</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Mystery value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.ip_address %></td>
        <td><%= location.country_code %></td>
        <td><%= location.country %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.mystery_value %></td>
        <td><%= link_to 'Show', location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Import data', import_data_path, method: :post %>

app/views/geolocation/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip address:</strong>
  <%= @location.ip_address %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @location.country_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Mystery value:</strong>
  <%= @location.mystery_value %>
</p>

<%= link_to 'Back', locations_path %>

app/views/layouts/geolocation/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geolocation</title>
  <%= stylesheet_link_tag    "geolocation/application", media: "all" %>
  <%= javascript_include_tag "geolocation/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>